### PR TITLE
Updated MSC Manifest to work with Serial/Hostname Configs

### PR DESCRIPTION
**Pull request by WardsParadox**
Updated Example Profile to work with new network configs

### CODE REVIEW

**Comment by ygini** [comment]
Could you change your script name and use your own github ID on it? This would make more sense.

**Comment by WardsParadox** [comment]
Rename the scripts to `com.github.wardsparadox.hello-it`?

**Comment by ygini** [comment]
Yes. It does not make sense (even if hosted in the main repo) to set my name on your work

**Comment by WardsParadox** [comment]
Want me to rename all of them as well?

**Comment by ygini** [comment]
Yes since it's your work it must be attributed to you (but not the plist since they are related to the software preference domain)

**Comment by WardsParadox** [comment]
Alright, I'll get on that 👍 and update the repo.

**Comment by WardsParadox** [comment]
@ygini Looks ready now to me. Fixed all requested.

**Comment by ygini** [comment]
Thanks a lot!

**Pull request merged**
